apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather-app
        image: abdelrahmangazy/weatherapp:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
