---
- name: Install Docker on Ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add vagrant user to Docker group
      user:
        name: vagrant
        group: docker

    - name: Pull Docker Image
      command: docker pull abdelrahmangazy/weatherapp:latest

    - name: Run Container
      command: docker run -d -p 5000:5000 abdelrahmangazy/weatherapp:latest

