---
- hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Fix dpkg interruptions (if any)
      command: dpkg --configure -a
      ignore_errors: yes  # Continue even if there are no interruptions

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Pull Docker Image
      command: docker pull abdelrahmangazy/weatherapp:latest

    - name: Run Container
      command: docker run -d -p 5000:5000 --name weatherapp --restart always abdelrahmangazy/weatherapp:latest

