---
- hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Fix dpkg interruptions (if any)
      command: dpkg --configure -a
      ignore_errors: yes  # Continue even if there are no interruptions

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: Remove existing image 
      command: docker rm -f weatherapp && docker rmi -f abdelrahmangazy/weatherapp
    - name: Get Image From Dockerhub
      command: docker pull abdelrahmangazy/weatherapp:latest
    - name: Run Container
      command: docker run -d -p 5000:5000 --name weatherapp abdelrahmangazy/weatherapp:latest
